[build]
  command = "npm run generate"
  publish = ".output/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/__nuxt"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*", 
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
