[build]
  command = "npm run build"
  publish = ".output/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/__nuxt"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/__nuxt"
  status = 200
